### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by khill-fbmc** [Pythagora-io/pythagora#10]
👋🏻 Hello,
I'm DrummerOfFenrir from reddit, here doing what I said. I installed the package to see whats what and my first hiccup is no TypeScript types 😢 
![image](https://user-images.githubusercontent.com/107003416/220705538-38e47082-b88b-48ef-9114-9a04f352f901.png)

I made this 

![image](https://user-images.githubusercontent.com/107003416/220706143-fd399205-514c-4277-a918-1c9f6c447cd9.png)

to eliminate those errors

![image](https://user-images.githubusercontent.com/107003416/220706235-7a5a48ba-8e4a-4be3-b90e-13246343a708.png)

so I will continue on.

### I'm using Next.JS and [trying this guide to get at the Next handler and use Express instead to add Pythagora](https://nextjs.org/docs/advanced-features/custom-server)

**Comment by zvone187** [comment]
Hey man, thanks for catching that. Yes, we're actually working on a support for Typescript at the moment - it should be out very soon. Btw, that's awesome that you were able to find your way through. How does it work? Also, what db are you using?

**Comment by zvone187** [comment]
Hmm, yes, that might be the problem. The next auth doesn't get captured. Although, that should fail while running tests and not while capturing. Were you able to run your app with Pythagora at all?

Btw, we just released the new version 0.0.28 in which express middlewares should work regardless of how is it called and we removed that one line of code (`if (global.Pythagora) global.Pythagora.setApp(server);`) so now, you can literally just run `npx pythagora --initScript ./your/server.js`.

**Comment by zvone187** [comment]
Hey, I'm so sorry for the late response. We're planning to devote time to debugging Typescript so wanted to get back to you then but we just haven't gotten to it yet (it's only 2 of us). Btw, we just released support for native Mongodb and we're aiming to launch on product hunt by the end of the month so my hope is to get into debugging ts then.

**Comment by LeonOstrez** [comment]
hey @khill-fbmc ! Thanks for trying Pythagora and putting time in testing it.

There is a new version (0.0.36) we released today and it should work with typescript. We tried it on some simple repository and it worked. If you find time you can try it out and let us know how it went.

Have in mind some things changed so you might have to check Readme again on how to use commands 😅

**Comment by zvone187** [comment]
Hi @khill-fbmc , I'm closing this issue since Typescript should be working but let us know if you need any other help.
