### ISSUE TITLE
Express won't start.

### ISSUE THREAD

**Issue by andrewtite-webonise** [Pythagora-io/pythagora#20]
Normally when I start my Express API Server, I get:
```
Connected Database: db1
Application running on port: 5001
```
But when I run `npx pythagora --initScript ./app/server.js --mode capture` it doesn't seem to hit the callback in `server.listen` and I get this instead:
```
Connected Database: db1
```

I'm running Express as an API server for a React frontend with a Postgres DB.
I'm trying to use this on my Express API Server.

Can you please help?
I'm not sure how to get this to work.
Thanks.

**Comment by zvone187** [comment]
Hi @andrewtite-webonise, thanks for bringing the convo here. What version of Pythagora are you using? We'll be releasing a new version today which might solve this issue.

**Comment by zvone187** [comment]
Hi Andrew, we just released it. You can install `pythagora@0.0.31`. With it, there are a couple of things changed (made easier). Now, you don't need to add any lines of code to your codebase + you can run pythagora with any command you're usually using to run your app.

For example, if you're running your app with "npm run start", now you run Pythagora with `npx pythagora --init-command "npm run start"`. We also added a couple more commands that you can see here - https://github.com/Pythagora-io/pythagora#-options

So, you can just do `npm i pythagora@0.0.31` and once that finishes run `npx pythagora --init-command "npm run start"` and you should be ready to go.

Let me know how it goes.

**Comment by andrewtite-webonise** [comment]
Do we need to do anything with authenticationMiddleware?

**Comment by zvone187** [comment]
Ah yes, you're right. We disabled Pythagora for any database other than Mongodb since tests can show they PASSED even when they aren't if the database is not being mocked. Sorry...but I'll make sure to ping you once we add Postgres - that should be in a month or two.

**Comment by andrewtite-webonise** [comment]
That extremely disappointing.
I was excited to show this off working on our project.

**Comment by zvone187** [comment]
😞 I'll try to get postreg support out asap...

**Comment by andrewtite-webonise** [comment]
Thanks, bud. I appreciate it.
Keep up the good work.
I'm very impressed with this project.
It will save SO MUCH development time writing tests!
Keep me posted.
I Can't wait to hear back from you.

**Comment by zvone187** [comment]
I'm closing this issue for now. Postgres is the next big feature we'll be implementing. Will update this issue once it's ready.
