### ISSUE TITLE
DOCS: can you share the tokens used/ price for the demo runs?

### ISSUE THREAD

**Issue by capaj** [Pythagora-io/pythagora#40]
for the lodash demo you have the runtime at 4 hours. So that sounds like you must have used quite a lot of tokens. 
Can you share how many tokens it consumes and how much does that cost in dollars?

**Comment by zvone187** [comment]
Hi @capaj, I don't know the exact number of tokens but the cost is something in the range of $10-$20 for the 1600 tests created for Lodash.
