### ISSUE TITLE
Use with Inversify?

### ISSUE THREAD

**Issue by drt1** [Pythagora-io/pythagora#7]
Hello,

is it possible to use pythagora with Inversify?

With Inversify there is no manual initialization of express like `let app = express();`
but there is an instance created of InversifyExpressServer and configuration is then
set by `InversifyExpressServer.setConfig(app => {... `
Then, the built in router in InversifyExpressServer is used to register the row controller on the root url.

thanks!

**Comment by LeonOstrez** [comment]
Hey @drt1 ,
Thank you so much for feedback and interest in Pythagora! It means a lot.

Unfortunately I don’t have any experience with Inversify and for now we haven’t tested any Inversify repository. Do you have any public repository that uses `InversifyExpressServer.setConfig(app => {…` as you mentioned that I could try? I would like to try setup Pythagora locally on that repo and let you know my progress.

best regards

**Comment by drt1** [comment]
Hi, 
unfortunately I don't have a public example available.
After short search i found this:
https://github.com/inversify/inversify-express-example/blob/master/Basic/bootstrap.ts

which looks similar, maybe it helps?

**Comment by LeonOstrez** [comment]
Hi @drt1,
we made some changes on how setup of Pythagora works and it should be a lot easier from now on! New version **pythagora@0.0.26** is live now!

No need to put this line
 `if (global.Pythagora) global.Pythagora.setApp(app);`
anymore while seting up Pythagora. From now on Pythagora works no matter how you use express (even if its used by other modules) which should cover your case also. Please let us know how your testing of Pythagora went.

Let us know if you have any further questions.
