### ISSUE TITLE
Configure with local LLM?

### ISSUE THREAD

**Issue by uninstallit** [Pythagora-io/pythagora#70]
Is it possible to configure with local llm - i.e.: Ollama or LlamaCpp servers? 

Some code cannot be sent to open apis. 

Thanks

**Comment by LeonOstrez** [comment]
yes it is.  Please check out [our wiki](https://github.com/Pythagora-io/gpt-pilot/wiki/Using-GPT%E2%80%90Pilot-with-Local-LLMs)
